### PR TITLE
Version03

### PR DESCRIPTION
**Pull request by rcjackson**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by rcjackson** [comment]
@conda-forge-admin, please rerender

**Comment by rcjackson** [comment]
@conda-forge-admin It seems like my recipe is failing due to an issue with matplotlib in the docker build. 

ImportError: libX11.so.6: cannot open shared object file: No such file or directory

**Comment by rcjackson** [comment]
@conda-forge-admin please rerender

**Comment by rcjackson** [comment]
@conda-forge/core Matplotlib fails to import in the docker environment. It looks like X11 is missing.

**Comment by jjhelmus** [comment]
Try adding a `yum_requirements.txt` file to the recipe with `mesa-libGL` and re-render the recipe.  See the conda-forge [documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html#yum-deps) for more details.

**Comment by rcjackson** [comment]
@conda-forge-admin please rerender

**Comment by rcjackson** [comment]
@conda-forge-admin please rerender

**Comment by rcjackson** [comment]
@conda-forge-admin please rerender

**Comment by rcjackson** [comment]
@conda-forge-admin please rerender

**Comment by rcjackson** [comment]
@conda-forge-admin please rerender

**Pull request closed without merging**
